apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tekkscope-search-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
spec:
  tls:
  - hosts:
    - search.tekkscope.com
    secretName: search-tekkscope-tls
  rules:
  - host: search.tekkscope.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: tekkscope-search-engine
            port:
              number: 80
